WebApplication3/Models/Movies/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Movies
{
    public class Movie
    {
        /// <summary>
        /// Movie id
        /// </summary>
        [Display(Name = "Id")]
        public int Id { get; set; }

        /// <summary>
        /// Movie poster 
        /// </summary>
        [Display(Name = "Url to poster")]
        public string Poster { get; set; }

        /// <summary>
        /// Movie name
        /// </summary>
        [Display(Name = "Movie name")]
        public string Name { get; set; }

        /// <summary>
        /// Author
        /// </summary>
        [Display(Name = "Author name")]
        public string Author { get; set; }

        /// <summary>
        /// Movie genere
        /// </summary>
        [Display(Name = "List of genres (by comma)")]
        public string Genre { get; set; }

        /// <summary>
        /// Creation date
        /// </summary>
        [Display(Name = "Release date")]
        public DateTime CreatedAt { get; set; }
    }
}

WebApplication3/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    [Route("[controller]/[action]")]
    public class CalculatorController : Controller
    {


        [Route("{firstNumber:int}/{secondNumber:int}")]
        public IActionResult Sum(int firstNumber, int secondNumber)
        {
            ViewData["action"] = RouteData.Values["action"].ToString();
            ViewData["mark"] = '+';
            ViewData["firstNumber"] = firstNumber;
            ViewData["secondNumber"] = secondNumber;
            ViewData["result"] = firstNumber + secondNumber;

            return View("Result");
        }

        [Route("{firstNumber:int}/{secondNumber:int:min(1)}")]
        public IActionResult Divide(int firstNumber, int secondNumber)
        {
            ViewData["action"] = RouteData.Values["action"].ToString();
            ViewData["mark"] = '/';
            ViewData["firstNumber"] = firstNumber;
            ViewData["secondNumber"] = secondNumber;
            ViewData["result"] = firstNumber / secondNumber;

            return View("Result");
        }


    }
}

WebApplication3/Controllers/HelloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1
{
    public class HelloController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApplication3/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    [Route("Say")]
    public class MessagesController : Controller
    {
        [Route("{**message}")]
        public IActionResult ShowMessage(string message)
        {
            if (string.IsNullOrEmpty(message))
            {
                ViewData["Message"] = "Message is empty";
            }
            else
            {
                ViewData["Message"] = message;
            }

            return View();
        }
    }
}

WebApplication3/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models.Movies;
using WebApplication3.Data;

namespace WebApplication1.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MoviesContext _dbContext;

        public MoviesController(MoviesContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            var movies = await _dbContext.Movies.ToListAsync();
            return View(movies);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Movie movie)
        {


            _dbContext.Movies.Add(movie);
            await _dbContext.SaveChangesAsync();

            var movies = await _dbContext.Movies.ToListAsync();

            return View("Index", movies);
        }

        public async Task<IActionResult> Search(string text)
        {
            text = text.ToLower();
            var searchedMovies = await _dbContext.Movies.Where(movie => movie.Name.ToLower().Contains(text)
                                            || movie.Genre.ToLower().Contains(text)
                                            || movie.Author.ToLower().Contains(text))
                                        .ToListAsync();
            return View("Index", searchedMovies);
        }

    }
}

WebApplication3/Views/Hello/Index.cshtml
<h1 class="title is-1">Hello from view with style</h1>

WebApplication3/Views/Shared/Add.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model WebApplication1.Models.Movies.Movie

@{
    ViewData["Title"] = "Add";
}

<h1 class="title is-1">Add</h1>

<h4 class="subtitle is-4">Movie</h4>
<hr />
<div class="column is-two-fifths">
    <div class="box">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="field">
                <label asp-for="Id" class="control-label"></label>
                <div class="control">
                    <input asp-for="Id" class="input" />
                    <span asp-validation-for="Id" class="has-text-danger"></span>
                </div>
            </div>
            <div class="field">
                <label asp-for="Poster" class="control-label"></label>
                <div class="control">
                    <input asp-for="Poster" class="input" />
                    <span asp-validation-for="Poster" class="has-text-danger"></span>
                </div>
            </div>
            <div class="field">
                <label asp-for="Name" class="control-label"></label>
                <div class="control">
                    <input asp-for="Name" class="input" />
                    <span asp-validation-for="Name" class="has-text-danger"></span>
                </div>
            </div>
            <div class="field">
                <label asp-for="Author" class="control-label"></label>
                <div class="control">
                    <input asp-for="Author" class="input" />
                    <span asp-validation-for="Author" class="has-text-danger"></span>
                </div>
            </div>
            <div class="field">
                <label asp-for="Genre" class="control-label"></label>
                <div class="control">
                    <input asp-for="Genre" class="input" />
                    <span asp-validation-for="Genre" class="has-text-danger"></span>
                </div>
            </div>
            <div class="field">
                <label asp-for="CreatedAt" class="control-label"></label>
                <div class="control">
                    <input asp-for="CreatedAt" class="input" />
                    <span asp-validation-for="CreatedAt" class="has-text-danger"></span>
                </div>
            </div>
            <div class="field is-grouped">
                <div class="control">
                    <button class="button is-link">Submit</button>
                </div>
            </div>


        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplication3/Views/Shared/Index.cshtml
@model IEnumerable<WebApplication1.Models.Movies.Movie>

@{
    ViewData["Title"] = "Movies";
}

<partial name="_Search" />


<h1>Index</h1>


<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poster)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    <img src="@item.Poster" asp-append-version="true">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplication3/Views/Shared/Result.cshtml
@{
    ViewData["Title"] = "Sum";
}

<h1 class="title is-1">@ViewData["action"]</h1>
<h2 class="subtitle is-2">@ViewData["firstNumber"] @ViewData["mark"] @ViewData["secondNumber"]  = @ViewData["result"]</h2>

WebApplication3/Views/Shared/ShowMessage.cshtml
@{
    ViewData["Title"] = "ShowMessage";
}

<h1 class="title is-1">@ViewData["Message"]</h1>

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Hello from view</title>
    <link rel="stylesheet" href="~/css/bulma.min.css">
</head>
<body>
    <div class="container">
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <strong class="title">My app</strong>
                </a>

                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                    @Html.ActionLink("10+5", "Sum", "Calculator", new { firstNumber = 10, secondNumber = 5 }, new { @class = "navbar-item" })
                    @Html.ActionLink("10+23", "Sum", "Calculator", new { firstNumber = 10, secondNumber = 23 }, new { @class = "navbar-item" })
                </div>

                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons">
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <div class="container">
        @RenderBody()
    </div>
</body>
</html>

WebApplication3/Views/Shared/_Search.cshtml
<br />
<form asp-action="Search" asp-controller="Movies" method="get">


    <div class="field has-addons">
        <div class="control">
            <input class="input" name="text" type="text" placeholder="Find a movie">
        </div>
        <div class="control">
            <button class="button is-info">
                Search
            </button>
        </div>
    </div>


</form>
<br />